# Generated by Django 5.1.7 on 2025-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kefalonia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
