# Generated by Django 5.1.7 on 2025-05-03 16:22

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kefalonia', '0002_place_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube',
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
